version: "3.9"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: diesel_demo
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 9Xu84SA1
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    networks:
      nw:
        ipv4_address: 172.10.0.2

  flat-backend:
    image: rust:latest
    container_name: flat
    working_dir: /app
    volumes:
      - ./flat_backend:/app
    tty: true
    environment:
      USER: "flat"
      CARGO_BUILD_TARGET_DIR: /flat_backend/target
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: cargo run
    networks:
      nw:
        ipv4_address: 172.10.1.2

networks:
  nw:
    external: true