version: "3.9"

services:
  flat-backend:
    build:
      context: .
      dockerfile: ./Docker/rust/Dockerfile
      target: prod
    container_name: flat
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      USER: "flat"
      CARGO_BUILD_TARGET_DIR: /target
      DATABASE_URL: mysql://docker:9Xu84SA1@mysql:3306/diesel_demo
      GIT_SSH_COMMAND: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
    secrets:
      - host_ssh_key
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: ./scripts/start.sh

  flat-backend-test:
    build:
      context: .
      dockerfile: ./Docker/rust/Dockerfile
      target: test
    container_name: flat-test
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      USER: "flat"
      CARGO_BUILD_TARGET_DIR: /target
      DATABASE_URL: mysql://docker:9Xu84SA1@mysql:3306/diesel_demo
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: ./scripts/start_test.sh

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: diesel_demo
      MYSQL_USER: docker
      MYSQL_PASSWORD: 9Xu84SA1
      MYSQL_ROOT_PASSWORD: 9Xu84SA1
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

secrets:
  host_ssh_key:
    file: ${SSH_KEY_PATH}