version: "3"

services:
  flat-backend:
    build:
      context: .
      dockerfile: ./Docker/rust/Dockerfile
      target: prod
    container_name: flat
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      USER: "flat"
      CARGO_BUILD_TARGET_DIR: /target
      DATABASE_URL: mysql://docker:9Xu84SA1@mysql:3306/diesel_demo
      SERAVICE_ACCOUNT: /path/to/service-account.json
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: ./scripts/start.sh
    secrets:
      - source: service_account_secrets
        target: service-account.json

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: diesel_demo
      MYSQL_USER: docker
      MYSQL_PASSWORD: 9Xu84SA1
      MYSQL_ROOT_PASSWORD: 9Xu84SA1
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=''

secrets:
  service_account_secrets:
    file: secrets/beacon-fun-2021-flat-4db603e2850a.json
