version: "3"

services:
  flat-backend:
    build:
      context: .
      dockerfile: ./Docker/rust/Dockerfile
      target: prod
    container_name: flat
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      USER: "flat"
      CARGO_BUILD_TARGET_DIR: /target
      # DATABASE_URL: mysql://docker:9Xu84SA1@mysql:3306/diesel_demo
      SERAVICE_ACCOUNT: /path/to/service-account.json
      BUCKET_NAME: icons_bucket
      MYSQL_USER: docker
      MYSQL_HOST: mysql
      MYSQL_DATABASE: diesel_demo
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: ./scripts/start.sh
    secrets:
      - source: service_account_secrets
        target: service-account.json
      - source: MYSQL_PASSWORD_FILE
        target: MYSQL_PASSWORD_FILE

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: diesel_demo
      MYSQL_USER: docker
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_FILE
      TZ: "Asia/Tokyo"
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=''
    secrets:
      - source: MYSQL_PASSWORD_FILE
        target: MYSQL_PASSWORD_FILE

secrets:
  service_account_secrets:
    # file: secrets/beacon-fun-2021-flat-4db603e2850a.json
    file: secrets/dummy.json
  MYSQL_PASSWORD_FILE:
    file: secrets/MYSQL_PASSWORD_FILE.txt