version: '3'

services:
  flat-backend:
    build:
      context: .
      dockerfile: ./Docker/rust/Dockerfile
      target: test
    container_name: flat-test
    environment:
      USER: "flat"
      CARGO_BUILD_TARGET_DIR: /target
      BUCKET_NAME: icons_test_bucket
    command: ./scripts/start_test.sh
