-- Your SQL goes here
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    name TEXT NOT NULL,
    status INT NOT NULL DEFAULT 0,
    spot TEXT,
    icon_path TEXT NOT NULL,
    salt BINARY(64) NOT NULL,
    hash BINARY(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    logedin_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY(id)
);