blank_issues_enabled: true
contact_links:
  - name: Issue
    url: https://github.com/FLAT-ICT/FLAT-backend/issues/new?template=issue.md&projects=FLAT-ICT/projects/1&labels=バックエンド
    about: Issue Template