name: CI

on:
  push:
    branches:
      - feature/workflow_setting
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    #TODO Input 待ちが発生してしまう
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: bash
        run: docker-compose build
      - name: compose tests
        shell: bash
        run: docker-compose run flat-backend-test
