name: CI

on:
  push:
    branches:
      - feature/workflow_setting
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    #TODO Input 待ちが発生してしまう
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose tests
        shell: bash
        run: |
          docker-compose up --build flat-backend-test --exit-code-from flat-backend-test
