name: CI

on:
  push:
    branches:
      - feature/workflow_setting
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose tests
        shell: bash
        env: 
          SSH_KEY: ${{ secrets.PAT }}
          SSH_KEY_PATH: ./secret.txt
        run: | 
          echo ${{ env.SSH_KEY }} > ./secret.txt
          docker-compose build
          docker-compose run flat-backend-test
